export const SIGNIN_FAILED = "SIGNIN_FAILED";
export const EMAIL_EXIST = "EMAIL_EXIST";
export const ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED";
export const GET_USERS = "GET_USERS";
export const USER_SAVE = "USER_SAVE";
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";